spring:
  data:
    rest:
      base-path: /data-api
  datasource:
    generate-unique-name: false
    name: tacocloud

  artemis:
    mode: native
    broker-url: "tcp://127.0.0.1:8161"
    user: "diego"
    password: "diego"

taco:
  orders:
    pageSize: 5

logging:
 file:
   path:
   file: TacoCloud.log
 level:
   tacoCloud: DEBUG
