spring:
  data:
    rest:
      base-path: /data-api
  datasource:
  generate-unique-name: false
  name: tacocloud

taco:
  orders:
    pageSize: 5

logging:
 file:
   path:
   file: TacoCloud.log
 level:
   tacoCloud: DEBUG
